export const FETCH_LOGIN_START = 'FETCH_LOGIN_START';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAIL = 'FETCH_LOGIN_FAIL';

/**
 * Admin dashboard action types
 */
export const FETCH_ADMIN_DASH_WIDGET_START = 'FETCH_ADMIN_DASH_WIDGET_START';
export const FETCH_ADMIN_DASH_WIDGET_SUCCESS =
  'FETCH_ADMIN_DASH_WIDGET_SUCCESS';
export const FETCH_ADMIN_DASH_WIDGET_FAIL = 'FETCH_ADMIN_DASH_WIDGET_FAIL';

/**
 * Instructor dashboard action types
 */
export const FETCH_INSTRUCTOR_DASH_WIDGET_START =
  'FETCH_INSTRUCTOR_DASH_WIDGET_START';
export const FETCH_INSTRUCTOR_DASH_WIDGET_SUCCESS =
  'FETCH_INSTRUCTOR_DASH_WIDGET_SUCCESS';
export const FETCH_INSTRUCTOR_DASH_WIDGET_FAIL =
  'FETCH_INSTRUCTOR_DASH_WIDGET_FAIL';
