export const FETCH_LOGIN_START = 'FETCH_LOGIN_START';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAIL = 'FETCH_LOGIN_FAIL';

/**
 * Admin dashboard action types
 */
export const FETCH_ADMIN_DASH_WIDGET_START = 'FETCH_ADMIN_DASH_WIDGET_START';
export const FETCH_ADMIN_DASH_WIDGET_SUCCESS = 'FETCH_ADMIN_DASH_WIDGET_SUCCESS';
export const FETCH_ADMIN_DASH_WIDGET_FAIL = 'FETCH_ADMIN_DASH_WIDGET_FAIL';

/**
 * Admin dashboard action types for top studnet
 */
export const FETCH_ADMIN_DASH_TOP_STUDENT_START = 'FETCH_ADMIN_DASH_TOP_STUDENT_START';
export const FETCH_ADMIN_DASH_TOP_STUDENT_SUCCESS = 'FETCH_ADMIN_DASH_TOP_STUDENT_SUCCESS';
export const FETCH_ADMIN_DASH_TOP_STUDENT_FAIL = 'FETCH_ADMIN_DASH_TOP_STUDENT_FAIL';

/**
 * Admin dashboard action types for trend analysis
 */
export const FETCH_ADMIN_DASH_TREND_ANALYSIS_START = 'FETCH_ADMIN_DASH_TREND_ANALYSIS_START';
export const FETCH_ADMIN_DASH_TREND_ANALYSIS_SUCCESS = 'FETCH_ADMIN_DASH_TREND_ANALYSIS_SUCCESS';
export const FETCH_ADMIN_DASH_TREND_ANALYSIS_FAIL = 'FETCH_ADMIN_DASH_TREND_ANALYSIS_FAIL';

/**
 * Admin instructor data
 */
export const FETCH_ADMIN_INSTRUCTOR_DATA_START = 'FETCH_ADMIN_INSTRUCTOR_DATA_START';
export const FETCH_ADMIN_INSTRUCTOR_DATA_SUCCESS = 'FETCH_ADMIN_INSTRUCTOR_DATA_SUCCESS';
export const FETCH_ADMIN_INSTRUCTOR_DATA_FAIL = 'FETCH_ADMIN_INSTRUCTOR_DATA_FAIL';

/**
 * Admin instructor & students stats data
 */
export const FETCH_ADMIN_STATS_DATA_START = 'FETCH_ADMIN_STATS_DATA_START';
export const FETCH_ADMIN_STATS_DATA_SUCCESS = 'FETCH_ADMIN_STATS_DATA_SUCCESS';
export const FETCH_ADMIN_STATS_DATA_FAIL = 'FETCH_ADMIN_STATS_DATA_FAIL';

/**
 * Export report from stats reports
 */
export const FETCH_ADMIN_EXPORT_CSV_STATS_DATA_START = 'FETCH_ADMIN_EXPORT_CSV_STATS_DATA_START';
export const FETCH_ADMIN_EXPORT_CSV_STATS_DATA_SUCCESS = 'FETCH_ADMIN_EXPORT_CSV_STATS_DATA_SUCCESS';
export const FETCH_ADMIN_EXPORT_CSV_STATS_DATA_FAIL = 'FETCH_ADMIN_EXPORT_CSV_STATS_DATA_FAIL';

/**
 * Admin instructor create
 */
export const FETCH_ADMIN_INSTRUCTOR_CREATE_START = 'FETCH_ADMIN_INSTRUCTOR_CREATE_START';
export const FETCH_ADMIN_INSTRUCTOR_CREATE_SUCCESS = 'FETCH_ADMIN_INSTRUCTOR_CREATE_SUCCESS';
export const FETCH_ADMIN_INSTRUCTOR_CREATE_FAIL = 'FETCH_ADMIN_INSTRUCTOR_CREATE_FAIL';

/**
 * Admin student data
 */
export const FETCH_ADMIN_STUDENT_DATA_START = 'FETCH_ADMIN_STUDENT_DATA_START';
export const FETCH_ADMIN_STUDENT_DATA_SUCCESS = 'FETCH_ADMIN_STUDENT_DATA_SUCCESS';
export const FETCH_ADMIN_STUDENT_DATA_FAIL = 'FETCH_ADMIN_STUDENT_DATA_FAIL';

/**
 * Admin reports data
 */
export const FETCH_ADMIN_REPORTS_DATA_START = 'FETCH_ADMIN_REPORTS_DATA_START';
export const FETCH_ADMIN_REPORTS_DATA_SUCCESS = 'FETCH_ADMIN_REPORTS_DATA_SUCCESS';
export const FETCH_ADMIN_REPORTS_DATA_FAIL = 'FETCH_ADMIN_REPORTS_DATA_FAIL';

/**
 * instructor and student download
 */
export const FETCH_ADMIN_INSTRUCTOR_STUDENT_DOWNLOAD_START = 'FETCH_ADMIN_INSTRUCTOR_STUDENT_DOWNLOAD_START';
export const FETCH_ADMIN_INSTRUCTOR_STUDENT_DOWNLOAD_SUCCESS = 'FETCH_ADMIN_INSTRUCTOR_STUDENT_DOWNLOAD_SUCCESS';
export const FETCH_ADMIN_INSTRUCTOR_STUDENT_DOWNLOAD_FAIL = 'FETCH_ADMIN_INSTRUCTOR_STUDENT_DOWNLOAD_FAIL';


/**
 * Admin reports data download
 */
export const FETCH_ADMIN_REPORTS_VIEW_DOWNLOAD_START = 'FETCH_ADMIN_REPORTS_VIEW_DOWNLOAD_START';
export const FETCH_ADMIN_REPORTS_VIEW_DOWNLOAD_SUCCESS = 'FETCH_ADMIN_REPORTS_VIEW_DOWNLOAD_SUCCESS';
export const FETCH_ADMIN_REPORTS_VIEW_DOWNLOAD_FAIL = 'FETCH_ADMIN_REPORTS_VIEW_DOWNLOAD_FAIL';


/**
 * submission reports data download
 */
export const FETCH_ADMIN_REPORTS_VIEW_SUBMISSION_DOWNLOAD_START = 'FETCH_ADMIN_REPORTS_VIEW_SUBMISSION_DOWNLOAD_START';
export const FETCH_ADMIN_REPORTS_VIEW_SUBMISSION_DOWNLOAD_SUCCESS = 'FETCH_ADMIN_REPORTS_VIEW_SUBMISSION_DOWNLOAD_SUCCESS';
export const FETCH_ADMIN_REPORTS_VIEW_SUBMISSION_DOWNLOAD_FAIL = 'FETCH_ADMIN_REPORTS_VIEW_SUBMISSION_DOWNLOAD_FAIL';


/**
 * Admin edit table row
 */
export const FETCH_ADMIN_EDIT_ROW_START = 'FETCH_ADMIN_EDIT_ROW_START';
export const FETCH_ADMIN_EDIT_ROW_SUCCESS = 'FETCH_ADMIN_EDIT_ROW_SUCCESS';
export const FETCH_ADMIN_EDIT_ROW_FAIL = 'FETCH_ADMIN_EDIT_ROW_FAIL';


/**
 * Admin delete table row
 */
export const FETCH_ADMIN_DELETE_ROW_START = 'FETCH_ADMIN_DELETE_ROW_START';
export const FETCH_ADMIN_DELETE_ROW_SUCCESS = 'FETCH_ADMIN_DELETE_ROW_SUCCESS';
export const FETCH_ADMIN_DELETE_ROW_FAIL = 'FETCH_ADMIN_DELETE_ROW_FAIL';


/**
 * Admin delete table row
 */
export const FETCH_ADMIN_DELETE_STUDENT_ROW_START = 'FETCH_ADMIN_DELETE_STUDENT_ROW_START';
export const FETCH_ADMIN_DELETE_STUDENT_ROW_SUCCESS = 'FETCH_ADMIN_DELETE_STUDENT_ROW_SUCCESS';
export const FETCH_ADMIN_DELETE_STUDENT_ROW_FAIL = 'FETCH_ADMIN_DELETE_STUDENT_ROW_FAIL';


/**
 * Admin deactivate table row
 */
export const FETCH_ADMIN_DEACTIVATE_ROW_START = 'FETCH_ADMIN_DEACTIVATE_ROW_START';
export const FETCH_ADMIN_DEACTIVATE_ROW_SUCCESS = 'FETCH_ADMIN_DEACTIVATE_ROW_SUCCESS';
export const FETCH_ADMIN_DEACTIVATE_ROW_FAIL = 'FETCH_ADMIN_DEACTIVATE_ROW_FAIL';

/**
 * Instructor dashboard action types
 */
export const FETCH_INSTRUCTOR_DASH_WIDGET_START = 'FETCH_INSTRUCTOR_DASH_WIDGET_START';
export const FETCH_INSTRUCTOR_DASH_WIDGET_SUCCESS = 'FETCH_INSTRUCTOR_DASH_WIDGET_SUCCESS';
export const FETCH_INSTRUCTOR_DASH_WIDGET_FAIL = 'FETCH_INSTRUCTOR_DASH_WIDGET_FAIL';


/**
 * Instructor classes data
 */
export const FETCH_INSTRUCTOR_CLASSES_DATA_START = 'FETCH_INSTRUCTOR_CLASSES_DATA_START';
export const FETCH_INSTRUCTOR_CLASSES_DATA_SUCCESS = 'FETCH_INSTRUCTOR_CLASSES_DATA_SUCCESS';
export const FETCH_INSTRUCTOR_CLASSES_DATA_FAIL = 'FETCH_INSTRUCTOR_CLASSES_DATA_FAIL';

/**
 * Instructor create classes
 */
export const FETCH_INSTRUCTOR_CREATE_CLASSES_DATA_START = 'FETCH_INSTRUCTOR_CREATE_CLASSES_DATA_START';
export const FETCH_INSTRUCTOR_CREATE_CLASSES_DATA_SUCCESS = 'FETCH_INSTRUCTOR_CREATE_CLASSES_DATA_SUCCESS';
export const FETCH_INSTRUCTOR_CREATE_CLASSES_DATA_FAIL = 'FETCH_INSTRUCTOR_CREATE_CLASSES_DATA_FAIL';

/**
 * Instructor edit classes
 */
export const FETCH_INSTRUCTOR_EDIT_CLASS_DATA_START = 'FETCH_INSTRUCTOR_EDIT_CLASS_DATA_START';
export const FETCH_INSTRUCTOR_EDIT_CLASS_DATA_SUCCESS = 'FETCH_INSTRUCTOR_EDIT_CLASS_DATA_SUCCESS';
export const FETCH_INSTRUCTOR_EDIT_CLASS_DATA_FAIL = 'FETCH_INSTRUCTOR_EDIT_CLASS_DATA_FAIL';

/**
 * Instructor - role
 * Instructor delete classes
 */

export const FETCH_INSTRUCTOR_DELETE_CLASS_START = 'FETCH_INSTRUCTOR_DELETE_CLASS_START';
export const FETCH_INSTRUCTOR_DELETE_CLASS_SUCCESS = 'FETCH_INSTRUCTOR_DELETE_CLASS_SUCCESS';
export const FETCH_INSTRUCTOR_DELETE_CLASS_FAIL = 'FETCH_INSTRUCTOR_DELETE_CLASS_FAIL';

/**
 * Instructor classes > student data
 */
export const FETCH_INSTRUCTOR_STUDENTS_ASSIGNMENTS_DATA_START = 'FETCH_INSTRUCTOR_STUDENTS_ASSIGNMENTS_DATA_START';
export const FETCH_INSTRUCTOR_STUDENTS_ASSIGNMENTS_DATA_SUCCESS = 'FETCH_INSTRUCTOR_STUDENTS_ASSIGNMENTS_DATA_SUCCESS';
export const FETCH_INSTRUCTOR_STUDENTS_ASSIGNMENTS_DATA_FAIL = 'FETCH_INSTRUCTOR_STUDENTS_ASSIGNMENTS_DATA_FAIL';

/**
 * Instructor > myclasses create student 
 */
export const FETCH_INSTRUCTOR_CREATE_STUDENT_DATA_START = 'FETCH_INSTRUCTOR_CREATE_STUDENT_DATA_START';
export const FETCH_INSTRUCTOR_CREATE_STUDENT_DATA_SUCCESS = 'FETCH_INSTRUCTOR_CREATE_STUDENT_DATA_SUCCESS';
export const FETCH_INSTRUCTOR_CREATE_STUDENT_DATA_FAIL = 'FETCH_INSTRUCTOR_CREATE_STUDENT_DATA_FAIL';

/**
 * Instructor > myclasses create assignment 
 */
export const FETCH_INSTRUCTOR_CREATE_ASSIGNMENT_DATA_START = 'FETCH_INSTRUCTOR_CREATE_ASSIGNMENT_DATA_START';
export const FETCH_INSTRUCTOR_CREATE_ASSIGNMENT_DATA_SUCCESS = 'FETCH_INSTRUCTOR_CREATE_ASSIGNMENT_DATA_SUCCESS';
export const FETCH_INSTRUCTOR_CREATE_ASSIGNMENT_DATA_FAIL = 'FETCH_INSTRUCTOR_CREATE_ASSIGNMENT_DATA_FAIL';

/**
 * Instructor myfolder data
 */
export const FETCH_INSTRUCTOR_MY_FOLDERS_START = 'FETCH_INSTRUCTOR_MY_FOLDERS_START';
export const FETCH_INSTRUCTOR_MY_FOLDERS_SUCCESS = 'FETCH_INSTRUCTOR_MY_FOLDERS_SUCCESS';
export const FETCH_INSTRUCTOR_MY_FOLDERS_FAIL = 'FETCH_INSTRUCTOR_MY_FOLDERS_FAIL';

/**
 * Instructor create myfolder 
 */
export const FETCH_INSTRUCTOR_CREATE_MY_FOLDERS_START = 'FETCH_INSTRUCTOR_CREATE_MY_FOLDERS_START';
export const FETCH_INSTRUCTOR_CREATE_MY_FOLDERS_SUCCESS = 'FETCH_INSTRUCTOR_CREATE_MY_FOLDERS_SUCCESS';
export const FETCH_INSTRUCTOR_CREATE_MY_FOLDERS_FAIL = 'FETCH_INSTRUCTOR_CREATE_MY_FOLDERS_FAIL';

/**
 * Instructor myfolder > submissionlist 
 */
export const FETCH_INSTRUCTOR_MY_FOLDERS_SUBMISSION_LIST_START = 'FETCH_INSTRUCTOR_MY_FOLDERS_SUBMISSION_LIST_START';
export const FETCH_INSTRUCTOR_MY_FOLDERS_SUBMISSION_LIST_SUCCESS = 'FETCH_INSTRUCTOR_MY_FOLDERS_SUBMISSION_LIST_SUCCESS';
export const FETCH_INSTRUCTOR_MY_FOLDERS_SUBMISSION_LIST_FAIL = 'FETCH_INSTRUCTOR_MY_FOLDERS_SUBMISSION_LIST_FAIL';

/**
 * Students dashboard action types
 */
export const FETCH_STUDENT_DASHBOARD_WIDGET_START = 'FETCH_STUDENT_DASHBOARD_WIDGET_START';
export const FETCH_STUDENT_DASHBOARD_WIDGET_SUCCESS = 'FETCH_STUDENT_DASHBOARD_WIDGET_SUCCESS';
export const FETCH_STUDENT_DASHBOARD_WIDGET_FAIL = 'FETCH_STUDENT_DASHBOARD_WIDGET_FAIL';

/**
 * Students classes data
 */
export const FETCH_STUDENTS_CLASSES_DATA_START = 'FETCH_STUDENTS_CLASSES_DATA_START';
export const FETCH_STUDENTS_CLASSES_DATA_SUCCESS = 'FETCH_STUDENTS_CLASSES_DATA_SUCCESS';
export const FETCH_STUDENTS_CLASSES_DATA_FAIL = 'FETCH_STUDENTS_CLASSES_DATA_FAIL';

/**
 * Students submission history data
 */
export const FETCH_STUDENTS_SUBMISSION_DETAILS_START = 'FETCH_STUDENTS_SUBMISSION_DETAILS_START';
export const FETCH_STUDENTS_SUBMISSION_DETAILS_SUCCESS = 'FETCH_STUDENTS_SUBMISSION_DETAILS_SUCCESS';
export const FETCH_STUDENTS_SUBMISSION_DETAILS_FAIL = 'FETCH_STUDENTS_SUBMISSION_DETAILS_FAIL';

/**
 * Students submission header data
 */
export const FETCH_STUDENTS_SUBMISSION_DETAILS_HEADER_START = 'FETCH_STUDENTS_SUBMISSION_DETAILS_HEADER_START';
export const FETCH_STUDENTS_SUBMISSION_DETAILS_HEADER_SUCCESS = 'FETCH_STUDENTS_SUBMISSION_DETAILS_HEADER_SUCCESS';
export const FETCH_STUDENTS_SUBMISSION_DETAILS_HEADER_FAIL = 'FETCH_STUDENTS_SUBMISSION_DETAILS_HEADER_FAIL';

/**
 * Students new submission data
 */
export const FETCH_STUDENTS_NEW_SUBMISSION_START = 'FETCH_STUDENTS_NEW_SUBMISSION_START';
export const FETCH_STUDENTS_NEW_SUBMISSION_SUCCESS = 'FETCH_STUDENTS_NEW_SUBMISSION_SUCCESS';
export const FETCH_STUDENTS_NEW_SUBMISSION_FAIL = 'FETCH_STUDENTS_NEW_SUBMISSION_FAIL';

/**
 * Students submission header data download
 */
export const FETCH_STUDENTS_SUBMISSION_HISTORY_DOWNLOAD_START = 'FETCH_STUDENTS_SUBMISSION_HISTORY_DOWNLOAD_START';
export const FETCH_STUDENTS_SUBMISSION_HISTORY_DOWNLOAD_SUCCESS = 'FETCH_STUDENTS_SUBMISSION_HISTORY_DOWNLOAD_SUCCESS';
export const FETCH_STUDENTS_SUBMISSION_HISTORY_DOWNLOAD_FAIL = 'FETCH_STUDENTS_SUBMISSION_HISTORY_DOWNLOAD_FAIL';

/**
 * Students qna data
 */
export const FETCH_STUDENTS_QA_DETAILS_START = 'FETCH_STUDENTS_QA_DETAILS_START';
export const FETCH_STUDENTS_QA_DETAILS_SUCCESS = 'FETCH_STUDENTS_QA_DETAILS_SUCCESS';
export const FETCH_STUDENTS_QA_DETAILS_FAIL = 'FETCH_STUDENTS_QA_DETAILS_FAIL';

/**
 * Students qna answer data
 */
export const FETCH_STUDENTS_QA_ANSWER_DETAILS_START = 'FETCH_STUDENTS_QA_ANSWER_DETAILS_START';
export const FETCH_STUDENTS_QA_ANSWER_DETAILS_SUCCESS = 'FETCH_STUDENTS_QA_ANSWER_DETAILS_SUCCESS';
export const FETCH_STUDENTS_QA_ANSWER_DETAILS_FAIL = 'FETCH_STUDENTS_QA_ANSWER_DETAILS_FAIL';

/**
 * Students feedback data
 */
export const FETCH_STUDENTS_FEEDBACK_DETAILS_START = 'FETCH_STUDENTS_FEEDBACK_DETAILS_START';
export const FETCH_STUDENTS_FEEDBACK_DETAILS_SUCCESS = 'FETCH_STUDENTS_FEEDBACK_DETAILS_SUCCESS';
export const FETCH_STUDENTS_FEEDBACK_DETAILS_FAIL = 'FETCH_STUDENTS_FEEDBACK_DETAILS_FAIL';

/**
 * Students assignments data
 */
export const FETCH_STUDENTS_ASSIGNMENT_DATA_START = 'FETCH_STUDENTS_ASSIGNMENT_DATA_START';
export const FETCH_STUDENTS_ASSIGNMENT_DATA_SUCCESS = 'FETCH_STUDENTS_ASSIGNMENT_DATA_SUCCESS';
export const FETCH_STUDENTS_ASSIGNMENT_DATA_FAIL = 'FETCH_STUDENTS_ASSIGNMENT_DATA_FAIL';


/**
 * Get Profile data
 */
export const FETCH_PROFILE_DATA_START = 'FETCH_PROFILE_DATA_START';
export const FETCH_PROFILE_DATA_SUCCESS = 'FETCH_PROFILE_DATA_SUCCESS';
export const FETCH_PROFILE_DATA_FAIL = 'FETCH_PROFILE_DATA_FAIL';


/**
 * Post Profile logo
 */
export const FETCH_PROFILE_LOGO_START = 'FETCH_PROFILE_LOGO_START';
export const FETCH_PROFILE_LOGO_SUCCESS = 'FETCH_PROFILE_LOGO_SUCCESS';
export const FETCH_PROFILE_LOGO_FAIL = 'FETCH_PROFILE_LOGO_FAIL';


/**
 * Post Profile name & password
 */
export const FETCH_PROFILE_CHANGE_PASSWORD_START = 'FETCH_PROFILE_CHANGE_PASSWORD_START';
export const FETCH_PROFILE_CHANGE_PASSWORD_SUCCESS = 'FETCH_PROFILE_CHANGE_PASSWORD_SUCCESS';
export const FETCH_PROFILE_CHANGE_PASSWORD_FAIL = 'FETCH_PROFILE_CHANGE_PASSWORD_FAIL';
