export const FETCH_LOGIN_START = 'FETCH_LOGIN_START';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAIL = 'FETCH_LOGIN_FAIL';

/**
 * Admin dashboard action types
 */
export const FETCH_ADMIN_DASH_WIDGET_START = 'FETCH_ADMIN_DASH_WIDGET_START';
export const FETCH_ADMIN_DASH_WIDGET_SUCCESS = 'FETCH_ADMIN_DASH_WIDGET_SUCCESS';
export const FETCH_ADMIN_DASH_WIDGET_FAIL = 'FETCH_ADMIN_DASH_WIDGET_FAIL';

/**
 * Admin dashboard action types for top studnet
 */
export const FETCH_ADMIN_DASH_TOP_STUDENT_START = 'FETCH_ADMIN_DASH_TOP_STUDENT_START';
export const FETCH_ADMIN_DASH_TOP_STUDENT_SUCCESS = 'FETCH_ADMIN_DASH_TOP_STUDENT_SUCCESS';
export const FETCH_ADMIN_DASH_TOP_STUDENT_FAIL = 'FETCH_ADMIN_DASH_TOP_STUDENT_FAIL';

/**
 * Admin dashboard action types for trend analysis
 */
export const FETCH_ADMIN_DASH_TREND_ANALYSIS_START = 'FETCH_ADMIN_DASH_TREND_ANALYSIS_START';
export const FETCH_ADMIN_DASH_TREND_ANALYSIS_SUCCESS = 'FETCH_ADMIN_DASH_TREND_ANALYSIS_SUCCESS';
export const FETCH_ADMIN_DASH_TREND_ANALYSIS_FAIL = 'FETCH_ADMIN_DASH_TREND_ANALYSIS_FAIL';

/**
 * Admin instructor data
 */
export const FETCH_ADMIN_INSTRUCTOR_DATA_START = 'FETCH_ADMIN_INSTRUCTOR_DATA_START';
export const FETCH_ADMIN_INSTRUCTOR_DATA_SUCCESS = 'FETCH_ADMIN_INSTRUCTOR_DATA_SUCCESS';
export const FETCH_ADMIN_INSTRUCTOR_DATA_FAIL = 'FETCH_ADMIN_INSTRUCTOR_DATA_FAIL';

/**
 * Admin student data
 */
export const FETCH_ADMIN_STUDENT_DATA_START = 'FETCH_ADMIN_STUDENT_DATA_START';
export const FETCH_ADMIN_STUDENT_DATA_SUCCESS = 'FETCH_ADMIN_STUDENT_DATA_SUCCESS';
export const FETCH_ADMIN_STUDENT_DATA_FAIL = 'FETCH_ADMIN_STUDENT_DATA_FAIL';

/**
 * Admin reports data
 */
export const FETCH_ADMIN_REPORTS_DATA_START = 'FETCH_ADMIN_REPORTS_DATA_START';
export const FETCH_ADMIN_REPORTS_DATA_SUCCESS = 'FETCH_ADMIN_REPORTS_DATA_SUCCESS';
export const FETCH_ADMIN_REPORTS_DATA_FAIL = 'FETCH_ADMIN_REPORTS_DATA_FAIL';

/**
 * Instructor dashboard action types
 */
export const FETCH_INSTRUCTOR_DASH_WIDGET_START = 'FETCH_INSTRUCTOR_DASH_WIDGET_START';
export const FETCH_INSTRUCTOR_DASH_WIDGET_SUCCESS = 'FETCH_INSTRUCTOR_DASH_WIDGET_SUCCESS';
export const FETCH_INSTRUCTOR_DASH_WIDGET_FAIL = 'FETCH_INSTRUCTOR_DASH_WIDGET_FAIL';


/**
 * Instructor classes data
 */
export const FETCH_INSTRUCTOR_CLASSES_DATA_START = 'FETCH_INSTRUCTOR_CLASSES_DATA_START';
export const FETCH_INSTRUCTOR_CLASSES_DATA_SUCCESS = 'FETCH_INSTRUCTOR_CLASSES_DATA_SUCCESS';
export const FETCH_INSTRUCTOR_CLASSES_DATA_FAIL = 'FETCH_INSTRUCTOR_CLASSES_DATA_FAIL';

/**
 * Instructor myfolder data
 */
export const FETCH_INSTRUCTOR_MY_FOLDERS_START = 'FETCH_INSTRUCTOR_MY_FOLDERS_START';
export const FETCH_INSTRUCTOR_MY_FOLDERS_SUCCESS = 'FETCH_INSTRUCTOR_MY_FOLDERS_SUCCESS';
export const FETCH_INSTRUCTOR_MY_FOLDERS_FAIL = 'FETCH_INSTRUCTOR_MY_FOLDERS_FAIL';
