/**
 * Download Original File data
 */
export const FETCH_DOWNLOAD_ORIGINAL_FILE_START = 'FETCH_DOWNLOAD_ORIGINAL_FILE_START';
export const FETCH_DOWNLOAD_ORIGINAL_FILE_SUCCESS = 'FETCH_DOWNLOAD_ORIGINAL_FILE_SUCCESS';
export const FETCH_DOWNLOAD_ORIGINAL_FILE_FAIL = 'FETCH_DOWNLOAD_ORIGINAL_FILE_FAIL';

/**
 * Download CSV
 */
export const FETCH_DOWNLOAD_CSV_START = 'FETCH_DOWNLOAD_CSV_START';
export const FETCH_DOWNLOAD_CSV_SUCCESS = 'FETCH_DOWNLOAD_CSV_SUCCESS';
export const FETCH_DOWNLOAD_CSV_FAIL = 'FETCH_DOWNLOAD_CSV_FAIL';

/**
 * Folder submission list
 */
export const FETCH_FOLDER_SUBMISSION_LIST_START = 'FETCH_FOLDER_SUBMISSION_LIST_START';
export const FETCH_FOLDER_SUBMISSION_LIST_SUCCESS = 'FETCH_FOLDER_SUBMISSION_LIST_SUCCESS';
export const FETCH_FOLDER_SUBMISSION_LIST_FAIL = 'FETCH_FOLDER_SUBMISSION_LIST_FAIL';

/**
 * Folder submission list
 */
export const FETCH_FOLDER_SUBMISSION_LIST_DELETE_START = 'FETCH_FOLDER_SUBMISSION_LIST_DELETE_START';
export const FETCH_FOLDER_SUBMISSION_LIST_DELETE_SUCCESS = 'FETCH_FOLDER_SUBMISSION_LIST_DELETE_SUCCESS';
export const FETCH_FOLDER_SUBMISSION_LIST_DELETE_FAIL = 'FETCH_FOLDER_SUBMISSION_LIST_DELETE_FAIL';

/**
 * Download grammar submission list
 */
 export const FETCH_GRAMMAR_REPORT_START = 'FETCH_GRAMMAR_REPORT_START';
 export const FETCH_GRAMMAR_REPORT_SUCCESS = 'FETCH_GRAMMAR_REPORT_SUCCESS';
 export const FETCH_GRAMMAR_REPORT_FAIL = 'FETCH_GRAMMAR_REPORT_FAIL';
 
 /**
 * Save to repository
 */
export const FETCH_SAVE_TO_REPOSITORY_START = 'FETCH_SAVE_TO_REPOSITORY_START';
export const FETCH_SAVE_TO_REPOSITORY_SUCCESS = 'FETCH_SAVE_TO_REPOSITORY_SUCCESS';
export const FETCH_SAVE_TO_REPOSITORY_FAIL = 'FETCH_SAVE_TO_REPOSITORY_FAIL';

/**
* Save to repository
*/
export const FETCH_DOCUMENT_TYPE_START = 'FETCH_DOCUMENT_TYPE_START';
export const FETCH_DOCUMENT_TYPE_SUCCESS = 'FETCH_DOCUMENT_TYPE_SUCCESS';
export const FETCH_DOCUMENT_TYPE_FAIL = 'FETCH_DOCUMENT_TYPE_FAIL';

