/**
 * Download Original File data
 */
export const FETCH_DOWNLOAD_ORIGINAL_FILE_START = 'FETCH_DOWNLOAD_ORIGINAL_FILE_START';
export const FETCH_DOWNLOAD_ORIGINAL_FILE_SUCCESS = 'FETCH_DOWNLOAD_ORIGINAL_FILE_SUCCESS';
export const FETCH_DOWNLOAD_ORIGINAL_FILE_FAIL = 'FETCH_DOWNLOAD_ORIGINAL_FILE_FAIL';


/**
 * Folder submission list
 */
export const FETCH_INSTRUCTOR_FOLDER_SUBMISSION_LIST_START = 'FETCH_INSTRUCTOR_FOLDER_SUBMISSION_LIST_START';
export const FETCH_INSTRUCTOR_FOLDER_SUBMISSION_LIST_SUCCESS = 'FETCH_INSTRUCTOR_FOLDER_SUBMISSION_LIST_SUCCESS';
export const FETCH_INSTRUCTOR_FOLDER_SUBMISSION_LIST_FAIL = 'FETCH_INSTRUCTOR_FOLDER_SUBMISSION_LIST_FAIL';

/**
 * Folder submission list
 */
export const FETCH_INSTRUCTOR_FOLDER_SUBMISSION_LIST_DELETE_START = 'FETCH_INSTRUCTOR_FOLDER_SUBMISSION_LIST_DELETE_START';
export const FETCH_INSTRUCTOR_FOLDER_SUBMISSION_LIST_DELETE_SUCCESS = 'FETCH_INSTRUCTOR_FOLDER_SUBMISSION_LIST_DELETE_SUCCESS';
export const FETCH_INSTRUCTOR_FOLDER_SUBMISSION_LIST_DELETE_FAIL = 'FETCH_INSTRUCTOR_FOLDER_SUBMISSION_LIST_DELETE_FAIL';