/**
 * Download Original File data
 */
export const FETCH_DOWNLOAD_ORIGINAL_FILE_START = 'FETCH_DOWNLOAD_ORIGINAL_FILE_START';
export const FETCH_DOWNLOAD_ORIGINAL_FILE_SUCCESS = 'FETCH_DOWNLOAD_ORIGINAL_FILE_SUCCESS';
export const FETCH_DOWNLOAD_ORIGINAL_FILE_FAIL = 'FETCH_DOWNLOAD_ORIGINAL_FILE_FAIL';

/**
 * Download CSV
 */
export const FETCH_DOWNLOAD_CSV_START = 'FETCH_DOWNLOAD_CSV_START';
export const FETCH_DOWNLOAD_CSV_SUCCESS = 'FETCH_DOWNLOAD_CSV_SUCCESS';
export const FETCH_DOWNLOAD_CSV_FAIL = 'FETCH_DOWNLOAD_CSV_FAIL';

/**
 * Folder submission list
 */
export const FETCH_FOLDER_SUBMISSION_LIST_START = 'FETCH_FOLDER_SUBMISSION_LIST_START';
export const FETCH_FOLDER_SUBMISSION_LIST_SUCCESS = 'FETCH_FOLDER_SUBMISSION_LIST_SUCCESS';
export const FETCH_FOLDER_SUBMISSION_LIST_FAIL = 'FETCH_FOLDER_SUBMISSION_LIST_FAIL';

/**
 * Folder submission list
 */
export const FETCH_FOLDER_SUBMISSION_LIST_DELETE_START = 'FETCH_FOLDER_SUBMISSION_LIST_DELETE_START';
export const FETCH_FOLDER_SUBMISSION_LIST_DELETE_SUCCESS = 'FETCH_FOLDER_SUBMISSION_LIST_DELETE_SUCCESS';
export const FETCH_FOLDER_SUBMISSION_LIST_DELETE_FAIL = 'FETCH_FOLDER_SUBMISSION_LIST_DELETE_FAIL';

/**
 * Download grammar submission list
 */
 export const FETCH_GRAMMAR_REPORT_START = 'FETCH_GRAMMAR_REPORT_START';
 export const FETCH_GRAMMAR_REPORT_SUCCESS = 'FETCH_GRAMMAR_REPORT_SUCCESS';
 export const FETCH_GRAMMAR_REPORT_FAIL = 'FETCH_GRAMMAR_REPORT_FAIL';
 
 /**
 * Save to repository
 */
export const FETCH_SAVE_TO_REPOSITORY_START = 'FETCH_SAVE_TO_REPOSITORY_START';
export const FETCH_SAVE_TO_REPOSITORY_SUCCESS = 'FETCH_SAVE_TO_REPOSITORY_SUCCESS';
export const FETCH_SAVE_TO_REPOSITORY_FAIL = 'FETCH_SAVE_TO_REPOSITORY_FAIL';

/**
* Submission history
*/
export const FETCH_SUBMISSION_HISTORY_START = 'FETCH_SUBMISSION_HISTORY_START';
export const FETCH_SUBMISSION_HISTORY_SUCCESS = 'FETCH_SUBMISSION_HISTORY_SUCCESS';
export const FETCH_SUBMISSION_HISTORY_FAIL = 'FETCH_SUBMISSION_HISTORY_FAIL';

/**
* Document type
*/
export const FETCH_DOCUMENT_TYPE_START = 'FETCH_DOCUMENT_TYPE_START';
export const FETCH_DOCUMENT_TYPE_SUCCESS = 'FETCH_DOCUMENT_TYPE_SUCCESS';
export const FETCH_DOCUMENT_TYPE_FAIL = 'FETCH_DOCUMENT_TYPE_FAIL';

/**
* Department type
*/
export const FETCH_DEPARTMENT_TYPE_START = 'FETCH_DEPARTMENT_TYPE_START';
export const FETCH_DEPARTMENT_TYPE_SUCCESS = 'FETCH_DEPARTMENT_TYPE_SUCCESS';
export const FETCH_DEPARTMENT_TYPE_FAIL = 'FETCH_DEPARTMENT_TYPE_FAIL';

/**
* Submission report bulk download
*/
export const FETCH_SUBMISSION_BULK_REPORT_START = 'FETCH_SUBMISSION_BULK_REPORT_START';
export const FETCH_SUBMISSION_BULK_REPORT_SUCCESS = 'FETCH_SUBMISSION_BULK_REPORT_SUCCESS';
export const FETCH_SUBMISSION_BULK_REPORT_FAIL = 'FETCH_SUBMISSION_BULK_REPORT_FAIL';

/**
* Submission report download
*/
export const FETCH_SUBMISSION_REPORT_DOWNLOAD_START = 'FETCH_SUBMISSION_REPORT_DOWNLOAD_START';
export const FETCH_SUBMISSION_REPORT_DOWNLOAD_SUCCESS = 'FETCH_SUBMISSION_REPORT_DOWNLOAD_SUCCESS';
export const FETCH_SUBMISSION_REPORT_DOWNLOAD_FAIL = 'FETCH_SUBMISSION_REPORT_DOWNLOAD_FAIL';

/**
* submission reprocess
*/
export const FETCH_SUBMISSION_REPROCESS_START = 'FETCH_SUBMISSION_REPROCESS_START';
export const FETCH_SUBMISSION_REPROCESS_SUCCESS = 'FETCH_SUBMISSION_REPROCESS_SUCCESS';
export const FETCH_SUBMISSION_REPROCESS_FAIL = 'FETCH_SUBMISSION_REPROCESS_FAIL';

/**
 * MFA Activation
 */
export const FETCH_MFA_ACTIVATION_START = 'FETCH_MFA_ACTIVATION_START';
export const FETCH_MFA_ACTIVATION_SUCCESS = 'FETCH_MFA_ACTIVATION_SUCCESS';
export const FETCH_MFA_ACTIVATION_FAIL = 'FETCH_MFA_ACTIVATION_FAIL';

/**
 * MFA Login
 */
export const FETCH_MFA_LOGIN_START = 'FETCH_MFA_LOGIN_START';
export const FETCH_MFA_LOGIN_SUCCESS = 'FETCH_MFA_LOGIN_SUCCESS';
export const FETCH_MFA_LOGIN_FAIL = 'FETCH_MFA_LOGIN_FAIL';

/**
 * Create Announcements
 */
export const FETCH_CREATE_ANNOUNCEMENTS_START = 'FETCH_ANNOUNCEMENTS_START';
export const FETCH_CREATE_ANNOUNCEMENTS_SUCCESS = 'FETCH_ANNOUNCEMENTS_SUCCESS';
export const FETCH_CREATE_ANNOUNCEMENTS_FAIL = 'FETCH_ANNOUNCEMENTS_FAIL';

/**
 * Get announcement data
 */
export const FETCH_ANNOUNCEMENT_DATA_START = 'FETCH_ANNOUNCEMENT_DATA_START';
export const FETCH_ANNOUNCEMENT_DATA_SUCCESS = 'FETCH_ANNOUNCEMENT_DATA_SUCCESS';
export const FETCH_ANNOUNCEMENT_DATA_FAIL = 'FETCH_ANNOUNCEMENT_DATA_FAIL';
/**
 * Get My announcement data
 */
export const FETCH_MY_ANNOUNCEMENT_DATA_START = 'FETCH_MY_ANNOUNCEMENT_DATA_START';
export const FETCH_MY_ANNOUNCEMENT_DATA_SUCCESS = 'FETCH_MY_ANNOUNCEMENT_DATA_SUCCESS';
export const FETCH_MY_ANNOUNCEMENT_DATA_FAIL = 'FETCH_MY_ANNOUNCEMENT_DATA_FAIL';