/**
 * Language list
 */
export const FETCH_LANGUAGE_LIST_START = 'FETCH_LANGUAGE_LIST_START';
export const FETCH_LANGUAGE_LIST_SUCCESS = 'FETCH_LANGUAGE_LIST_SUCCESS';
export const FETCH_LANGUAGE_LIST_FAIL = 'FETCH_LANGUAGE_LIST_FAIL';

/**
 * Upload google drive
 */
export const FETCH_UPLOAD_GOOGLE_DRIVE_START = 'FETCH_UPLOAD_GOOGLE_DRIVE_START';
export const FETCH_UPLOAD_GOOGLE_DRIVE_SUCCESS = 'FETCH_UPLOAD_GOOGLE_DRIVE_SUCCESS';
export const FETCH_UPLOAD_GOOGLE_DRIVE_FAIL = 'FETCH_UPLOAD_GOOGLE_DRIVE_FAIL';

/**
 * Upload file non english
 */
 export const FETCH_UPLOAD_FILE_NON_ENGLISH_START = 'FETCH_UPLOAD_FILE_NON_ENGLISH_START';
 export const FETCH_UPLOAD_FILE_NON_ENGLISH_SUCCESS = 'FETCH_UPLOAD_FILE_NON_ENGLISH_SUCCESS';
 export const FETCH_UPLOAD_FILE_NON_ENGLISH_FAIL = 'FETCH_UPLOAD_FILE_NON_ENGLISH_FAIL';