const END_POINTS_PRO = {
    ADMIN_PROFILE_DATA: '/admin/accountInformation',
    ADMIN_PROFILE_UPLOAD_LOGO: '/admin/uploadLogo',
    ADMIN_DASHBOARD_WIDGET: '/admin/dashboard',
    ADMIN_TREND_ANALYSIS: '/admin/trendAnalysis',
    ADMIN_RENEW_ACCOUNT: '/admin/reviveValidity',
    ADMIN_USER: '/admin/users',
    ADMIN_USER_STATS: '/admin/user/stats/',
    ADMIN_EXPORT_CSV_STATS: '/admin/exportToCSV/',
    ACTIVATE_USER: '/admin/activateUser?id=',
    DEACTIVATE_USER: '/admin/deactivateUser?id=',
    CREATE_USER: '/admin/user',
    USER_DOWNLOAD_TEMPLATE: '/admin/userTemplate',
    CREATE_MULTIPLE_USER: '/admin/addMultipleUsers',
    ADMIN_USER_EDIT_DATA: '/admin/user/',
    ADMIN_USER_DELETE: '/admin/user?id=',
    ADMIN_REPORTS: '/admin/reports',
    ADMIN_REPORTS_DOWNLOAD_LIST: '/admin/',
    ADMIN_REPORTS_DOWNLOAD_USER_LIST: '/admin/downloadUsers',
    ADMIN_REPOSITARY_DATA: '/admin/directRepositoryInbox',
    ADMIN_REPOSITARY_UPLOAD_SINGLE_FILE: '/admin/directRepository/single',
    ADMIN_REPOSITARY_UPLOAD_MULTIPLE_FILE: '/admin/directRepository/multiple',
    ADMIN_REPOSITARY_UPLOAD_ZIP: '/admin/directRepository/zip',
    USER_REPOSITARY_UPLOAD_SINGLE_FILE: '/privateRepository/single',
    USER_REPOSITARY_UPLOAD_MULTIPLE_FILE: '/privateRepository/multiple',
    USER_REPOSITARY_UPLOAD_ZIP: '/privateRepository/zip',
    ADMIN_REPOSITARY_REMOVE: '/admin/removeRepository/',
    ADMIN_INTEGRATION_DATA: '/integrations/home',
    ADMIN_MOODLE_INTEGRATION: '/integrations/moodle',
    ADMIN_CANVAS_INTEGRATION: '/integrations/canvas',
    ADMIN_BLACKBOARD_INTEGRATION: '/integrations/blackboard',
    USERS_DASHBOARD_WIDGET: '/user/dashboard',
    USER_PROFILE_DATA: '/user/accountInformation',
    USER_MY_FOLDERS: '/folders',
    USER_FOLDER_EDIT_AND_DELETE_DATA: '/folder',
    CREATE_FOLDER: '/folder',
    USER_SUBMISSION: '/folder/',
    USER_SUBMISSION_LIST_DOWNLOAD: '/folderReport/',
    USER_REPOSITARY_DATA: '/privateRepositoryInbox',
    USER_REPOSITARY_REMOVE: '/removePrivateRepository/',
    USER_REPOSITARY_UPLOAD: '/privateRepository',
}

export default END_POINTS_PRO;