const END_POINTS = {
    LOGIN: '/authentication/authenticate',
    ADMIN_DASHBOARD_WIDGET: '/extreme/admin/dashboard',
    ADMIN_TOP_STUDENT: '/extreme/admin/topStudents',
    ADMIN_TREND_ANALYSIS: '/extreme/admin/trendAnalysis',
    ADMIN_INSTRUCTOR: '/extreme/admin/instructors',
    ADMIN_INSTRUCTOR_STUDENT_STATS: `/extreme/admin/instructor`,
    ADMIN_EXPORT_CSV_STATS: `/extreme/admin/exportToCSV`,
    ADMIN_STUDENT: '/extreme/admin/students',
    ADMIN_REPORTS: '/extreme/admin/reports',
    ADMIN_REPORTS_DOWNLOAD_INSTRUCTOR_LIST: '/extreme/admin/',
    ADMIN_REPORTS_DOWNLOAD_STUDENTS_LIST: '/extreme/admin/students/download',
    ADMIN_INSTRUCTOR_DELETE: '/extreme/admin/instructor',
    ADMIN_STUDENT_DELETE: '/extreme/admin/student',
    INSTRUCTOR_DASHBOARD_WIDGET: '/extreme/instructor/dashboard',
    INSTRUCTOR_MY_CLASSES: '/extreme/instructor/classes',
    INSTRUCTOR_MY_FOLDERS: '/extreme/instructor/myFolders',
    STUDENT_MY_CLASSES: '/extreme/student/classes',
    STUDENT_MY_ASSIGNMENTS: '/extreme/student/myassignments',
    STUDENT_MY_ASSIGNMENTS_SUBMISSION: '/extreme/student/myassignments-details',
    PROFILE_DATA: '/extreme/admin/accountInformation',
    ADMIN_PROFILE_UPLOAD_LOGO:'/extreme/admin/uploadLogo',
    PROFILE_CHANGE_PASSWORD: '/extreme/account/password',
    EDIT_DATA: '/extreme/admin/edit',
    ACTIVATE_DEACTIVATE_INSTRUCTOR: '/extreme/admin/instructor',
    CREATE_INSTRUCTOR: '/extreme/admin/instructor',
    CREATE_CLASS: '/extreme/instructor/class',
    CREATE_FOLDER: '/extreme/instructor/myFolder',
    CREATE_STUDENT: '/extreme/instructor/classes/student',
    CREATE_ASSIGNMENT: '/extreme/instructor/classes/assignment',
};

export default END_POINTS;
